### ISSUE TITLE
can't start gulp

### ISSUE THREAD

**Issue by titaniumbones** [mozilla/popcorn-editor#1]
hi, just trying this out to see if I can use it for a class. I did 

``` sh
git clone https://github.com/Nolski/popcorn-editor.git
cd popcorn-editor
npm install gulp
gulp
```

and I get:

```
✗ gulp 
module.js:338
    throw err;
          ^
Error: Cannot find module 'gulp-less'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/matt/src/popcorn-editor/gulpfile.js:2:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

instructions or clues? thx,
matt

**Comment by Nolski** [comment]
Try running `npm install` to install all of the gulp modules and then run `gulp`. I'll update the README to reflect this :)

**Comment by titaniumbones** [comment]
On 13/07/15 05:38 PM, Mike Nolan wrote:

> Try running |npm install| to install all of the gulp modules

That gives:

```
cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/bin/npm', 'install' ]
2 info using npm@2.12.0
3 info using node@v0.12.4
4 verbose readDependencies loading dependencies from
/home/matt/src/popcorn-editor/package.json
5 error install Couldn't read dependencies
6 verbose stack Error: Invalid name: "Popcorn Editor"
6 verbose stack     at ensureValidName
(/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:331:15)
6 verbose stack     at Object.module.exports.fixNameField
(/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:210:5)
6 verbose stack     at
/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
6 verbose stack     at Array.forEach (native)
6 verbose stack     at normalize
(/usr/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
6 verbose stack     at final
(/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
6 verbose stack     at then
(/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
6 verbose stack     at
/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
6 verbose stack     at evalmachine.<anonymous>:334:14
6 verbose stack     at
/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:102:5
7 verbose cwd /home/matt/src/popcorn-editor
8 error Linux 4.0.5-1-ARCH
9 error argv "node" "/usr/bin/npm" "install"
10 error node v0.12.4
11 error npm  v2.12.0
12 error Invalid name: "Popcorn Editor"
13 error If you need help, you may report this error at:
13 error     <https://github.com/npm/npm/issues>
14 verbose exit [ 1, true ]
```

I tried upgrading npm to 2.13 & node to 0.12.7, with no change.  I don't
know that much about node but I changed the name to PopcornEditor and
was able to get everything to install.  Not sure how to run it locally
(is that possible?), but threw the whole directory on the server and was
able to see the interface, at least.

**Comment by stuff** [comment]
name of the project in the package.json file is invalid (it must not contains a space) you can change that locally to test

**Comment by Nolski** [comment]
Good catch. Sorry it took me a few to get back to ya.

**Comment by titaniumbones** [comment]
NP, thx for the fix!
